# global options
dist: xenial
language:
  - c
compiler:
  - gcc
cache:
  directories:
    - "${HOME}/persist"
env:
  global:
    - MAKEOPTS="-j4"
git:
  submodules: false

# define the successive stages
stages:
  - name: test

# define the jobs for the stages
# order of the jobs has longest running first to optimise total time
jobs:
  include:
    # esp32 port
    - stage: test
      env: NAME="esp32 port build"
      install:
        - sudo apt-get install python3-pip
        - sudo pip3 install pyparsing
        - wget https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
        - zcat xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz | tar x
        - export PATH=$(pwd)/xtensa-esp32-elf/bin:$PATH
        - git clone https://github.com/espressif/esp-idf.git
        - git -C esp-idf checkout $(grep "ESPIDF_SUPHASH :=" ports/esp32/Makefile | cut -d " " -f 3)
        - git -C esp-idf submodule update --init components/json/cJSON components/esp32/lib components/esptool_py/esptool components/expat/expat components/lwip/lwip components/mbedtls/mbedtls components/micro-ecc/micro-ecc components/nghttp/nghttp2
      script:
        - git submodule update --init lib/berkeley-db-1.xx
        - make ${MAKEOPTS} -C mpy-cross
        - make ${MAKEOPTS} -C ports/esp32 ESPIDF=$(pwd)/esp-idf
        - mkdir bin-export
        - ls
        - mv ports/esp32/build-GENERIC/firmware.bin bin-export/firmware.bin
        - mv ports/esp32/build-GENERIC/application.bin bin-export/application.bin
        - mv ports/esp32/build-GENERIC/application.elf bin-export/application.elf
        - mv ports/esp32/build-GENERIC/bootloader.bin bin-export/bootloader.bin
        - mv ports/esp32/build-GENERIC/bootloader.elf bin-export/bootloader.elf
        - mv ports/esp32/build-GENERIC/bootloader.map bin-export/bootloader.map
      deploy:
        provider: s3
        access_key_id: "$YOUR_AWS_ACCESS_KEY"
        secret_access_key: "$YOUR_AWS_SECRET_KEY"
        bucket: "esp32-test"
        region: us-west-1
        skip_cleanup: true
        upload_dir: bin-export
